CREATE TABLE dim_articles(
    sid INT GENERATED BY DEFAULT AS IDENTITY
    ,nid INT NOT NULL
    ,crt_dt DATE NOT NULL
    ,mod_dt DATE NOT NULL
    ,author VARCHAR2(128) NOT NULL
    ,title VARCHAR2(50) NOT NULL
    ,content CLOB NOT NULL
    ,start_dt DATE DEFAULT CURRENT_TIMESTAMP NOT NULL
    ,end_dt DATE DEFAULT NULL
    ,is_act_ind NUMBER(1) DEFAULT 1
    ,CONSTRAINT ch_is_act_ind_dim_articles
        CHECK(is_act_ind = 1 OR is_act_ind IS NULL)
    ,PRIMARY KEY(sid)
    );

CREATE TABLE f_article_comment(
    sid INT GENERATED BY DEFAULT AS IDENTITY
    ,article_sid INT NOT NULL
    ,date_id INT NOT NULL
    ,comment_id INT NOT NULL
    ,time_ival INTERVAL DAY TO SECOND NOT NULL
    ,rating INT
    ,votes INT
    ,content CLOB NOT NULL
    ,action_type CHAR(1) NOT NULL
    ,CONSTRAINT ch_action_type_f_article_comment
        CHECK(action_type IN ('I', 'U', 'D'))
    ,CONSTRAINT article_sid_FK_f_article_comment
        FOREIGN KEY (article_sid) REFERENCES dim_articles(sid)
    ,CONSTRAINT date_id_FK_f_article_comment
        FOREIGN KEY (date_id) REFERENCES dim_dates(id)
    ,PRIMARY KEY(sid)
    );

CREATE TABLE dim_dates(
    id INT
    ,d_date DATE NOT NULL
    ,d_year INT NOT NULL
    ,half_year INT NOT NULL
    ,d_quarter INT NOT NULL
    ,d_month INT NOT NULL
    ,name_month VARCHAR2(20) NOT NULL
    ,d_day INT NOT NULL
    ,d_week INT NOT NULL
    ,begin_of_month INT NOT NULL
    ,end_of_month INT NOT NULL
    ,PRIMARY KEY(id)
    );

CREATE OR REPLACE FUNCTION date_to_int RETURN INT IS
BEGIN
    RETURN TO_NUMBER(TO_CHAR(SYSDATE, 'DDMMYYYY'));
END;
