CREATE TABLE article(
    id INT GENERATED BY DEFAULT AS IDENTITY
    ,crt_dt DATE DEFAULT SYSDATE NOT NULL
    ,mod_dt DATE DEFAULT SYSDATE NOT NULL
    ,author VARCHAR2(128) NOT NULL
    ,title VARCHAR2(50) NOT NULL
    ,content CLOB NOT NULL
    ,PRIMARY KEY(id)
    );

CREATE TABLE article_comment(
    id INT GENERATED BY DEFAULT AS IDENTITY
    ,article_id INT NOT NULL
    ,ts TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP NOT NULL
    ,reply_to_id INT
    ,rating INT
    ,votes INT
    ,commenter VARCHAR2(128) NOT NULL
    ,content CLOB NOT NULL
    ,like_amount INT NOT NULL
    ,dislike_amount INT NOT NULL
    ,CONSTRAINT reply_to_id_fk_article_comment
        FOREIGN KEY  (reply_to_id) REFERENCES article_comment(id)
    ,CONSTRAINT article_id_fk_article_comment
        FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE
    ,PRIMARY KEY(id)
    )
PARTITION BY RANGE (ts) (
    PARTITION part_outdated
    VALUES
        LESS THAN (TIMESTAMP '2023-01-01 00:00:00'),
    PARTITION part_2023
    VALUES
        LESS THAN (TIMESTAMP '2024-01-01 00:00:00'),
    PARTITION part_2024
    VALUES
        LESS THAN (TIMESTAMP '2025-01-01 00:00:00'),
    PARTITION part_2025
    VALUES
        LESS THAN (TIMESTAMP '2026-01-01 00:00:00'),
    PARTITION part_upcoming
    VALUES
        LESS THAN (MAXVALUE)
    );

CREATE OR REPLACE FUNCTION get_random_number RETURN NUMBER IS
BEGIN
    RETURN TRUNC(DBMS_RANDOM.VALUE(1, 100));
END;

CREATE TABLE audit_action(
    id INT GENERATED BY DEFAULT AS IDENTITY
    ,ts TIMESTAMP(0) NOT NULL
    ,table_name VARCHAR2(128) NOT NULL
    ,row_id INT NOT NULL
    ,user_name VARCHAR2(128) NOT NULL
    ,action_type CHAR(1) NOT NULL
    ,action_summary VARCHAR2(250) NOT NULL
    ,CONSTRAINT ch_action_type_audit_action
        CHECK(action_type IN ('I', 'U', 'D'))
    ,PRIMARY KEY (id)
    );