CREATE user SCD identified  by "qwer.12345A"    ;

CREATE TABLE SCD.dim_article(
    SID INT GENERATED BY DEFAULT AS IDENTITY,
    COL_nid INT NOT NULL,
    COL_crt_dt DATE NOT NULL,
    COL_mod_dt DATE NOT NULL,
    COL_author VARCHAR2(128) NOT NULL,
    COL_title VARCHAR2(50) NOT NULL,
    COL_content CLOB NOT NULL,
    COL_start_dt DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COL_end_dt DATE DEFAULT NULL,
    COL_is_act_ind NUMBER(1) default 1,
    CONSTRAINT TAB_dim_article_CK_is_act_ind CHECK (COL_is_act_ind IN (1,0)),
    CONSTRAINT tab_dim_article_pk PRIMARY KEY (SID)
);


CREATE TABLE SCD.DIM_DATES(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    COL_D_DATE DATE NOT NULL,
    COL_D_YEAR INT NOT NULL,
    COL_HALF_YEAR INT NOT NULL,
    COL_D_QUARTER INT NOT NULL,
    COL_D_MONTH INT NOT NULL,
    COL_NAME_MONTH VARCHAR2(20) NOT NULL,
    COL_d_day INT NOT NULL,
    COL_D_WEEK INT NOT NULL,
    COL_begin_of_month INT NOT NULL,
    COL_end_of_month INT NOT NULL,
    CONSTRAINT TAB_DIM_DATES_PK
        PRIMARY KEY(ID));
CREATE TABLE SCD.f_article_comment (
    sid INT GENERATED BY DEFAULT AS IDENTITY,
    COL_ARTICLE_SID INT NOT NULL,
    COL_DATE_ID INT NOT NULL,
    COL_comment_id INT NOT NULL,
    COL_time_ival interval day to second NOT NULL,
    COL_rating INT NOT NULL,
    COL_votes INT NOT NULL,
    COL_content CLOB NOT NULL,
    COL_action_type CHAR(1),
    CONSTRAINT tab_f_article_comment_ck_action_type CHECK (col_action_type IN ('I', 'U', 'D')),
    CONSTRAINT f_article_comment_FK_dim_article FOREIGN KEY (COL_ARTICLE_SID) REFERENCES SCD.dim_article(SID),
    CONSTRAINT f_article_comment_FK_DIM_DATES FOREIGN KEY (COL_DATE_ID) REFERENCES SCD.DIM_DATES(ID),
    CONSTRAINT TAB_f_article_comment_PK PRIMARY KEY (SID)
);

CREATE OR REPLACE PACKAGE etl_blog AS
    PROCEDURE etl_load_articles;
    PROCEDURE etl_load_comments;
END etl_blog;

CREATE OR REPLACE PACKAGE BODY etl_blog AS
  PROCEDURE etl_load_articles IS
    CURSOR c_articles IS SELECT DISTINCT id FROM BLOG_BASE.ARTICLE;
    count_dim_article_row int;
BEGIN
    FOR article_rec IN c_articles LOOP


      --посдание мне из будущего сделать select где мы сравниваем дату последнего апдейта и даты начала из dim_article
      select COUNT(*) into count_dim_article_row from dim_article da inner join BLOG_BASE.ARTICLE aa on aa.ID = da.COL_nid where da.COL_nid = article_rec.ID  and (aa.COL_CRT_DT = da.COL_crt_dt OR aa.COL_MOD_DT = da.COL_crt_dt);
      DBMS_OUTPUT.PUT_LINE(count_dim_article_row);
        IF count_dim_article_row = 0 THEN

            UPDATE SCD.dim_article
            SET COL_end_dt = CURRENT_TIMESTAMP, COL_is_act_ind = NULL
            WHERE COL_is_act_ind = 1 AND COL_nid = article_rec.id;
            INSERT INTO SCD.dim_article(COL_nid, COL_crt_dt, COL_mod_dt, COL_author, COL_title, COL_content)
        SELECT id, COL_crt_dt, COL_mod_dt, COL_author, COL_title, COL_contenT
        FROM BLOG_BASE.ARTICLE
        WHERE id = article_rec.id;
        END IF;
    END LOOP;
END etl_load_articles;


 PROCEDURE etl_load_comments IS
BEGIN
    MERGE INTO f_article_comment dst
    USING (
        SELECT
            ac.id AS comment_id,
            D.SID AS article_sid,
            dd.id AS date_id,
           NUMTODSINTERVAL(EXTRACT(DAY FROM ac.col_ts), 'DAY')
            + NUMTODSINTERVAL(EXTRACT(HOUR FROM ac.col_ts), 'HOUR')
            + NUMTODSINTERVAL(EXTRACT(MINUTE FROM ac.col_ts), 'MINUTE')
            + NUMTODSINTERVAL(EXTRACT(SECOND FROM ac.col_ts), 'SECOND')
            AS time_ival,
            ac.col_rating AS rating,
            ac.col_votes AS votes,
            ac.col_content AS content,
            aa.col_action_type AS action_type
        FROM BLOG_BASE.article_comment ac
        JOIN BLOG_BASE.article a ON ac.col_article_id = a.id
         JOIN dim_dates dd ON  trunc(ac.col_ts)= dd.COL_D_DATE
        JOIN BLOG_BASE.audit_action aa ON ac.id = aa.col_table_id
        JOIN DIM_ARTICLE D on a.COL_AUTHOR = D.COL_AUTHOR
        WHERE aa.id = (SELECT MAX(id) FROM BLOG_BASE.audit_action WHERE col_table_id = ac.id)
    ) src
    ON (dst.COL_comment_id = src.comment_id)
    WHEN MATCHED THEN
        UPDATE SET
            dst.COL_article_sid = src.article_sid,
            dst.COL_time_ival = src.time_ival,
            dst.COL_rating = src.rating,
            dst.COL_votes = src.votes,
            dst.COL_content = src.content,
            dst.COL_action_type = src.action_type
    WHEN NOT MATCHED THEN
        INSERT (
            col_article_sid,
            col_date_id,
            col_comment_id,
            col_time_ival,
            col_rating,
            col_votes,
            col_content,
            col_action_type
        ) VALUES (
            src.article_sid,
            src.date_id,
            src.comment_id,
            src.time_ival,
            src.rating,
            src.votes,
            src.content,
            src.action_type
        );

    COMMIT;
END etl_load_comments;
END etl_blog;


BEGIN
    SCD.etl_blog.ETL_LOAD_ARTICLES();
    SCD.ETL_BLOG.ETL_LOAD_COMMENTS();
commit ;
end;




BEGIN

  DBMS_SCHEDULER.CREATE_PROGRAM (
    program_name        => 'JOB_1',
    program_type        => 'PLSQL_BLOCK',
    program_action      => 'BEGIN SCD.etl_blog.ETL_LOAD_COMMENTS(); END;',
    enabled         => TRUE
  );

  DBMS_SCHEDULER.CREATE_PROGRAM (
    program_name        => 'JOB_2',
    program_type        => 'PLSQL_BLOCK',
    program_action      => 'BEGIN SCD.etl_blog.etl_load_articles; END;',
    enabled         => FALSE
     -- Второе задание начнет выполняться только после успешного завершения первого
  );
dbms_scheduler.create_chain(
         chain_name => 'DEMO_CHAIN'
     );
   dbms_scheduler.define_chain_step(
               chain_name => 'DEMO_CHAIN',
               step_name => 'DEMO_S_etl_load_articles',
               program_name => 'JOB_1'
           );
  dbms_scheduler.define_chain_step(
               chain_name => 'DEMO_CHAIN',
               step_name => 'DEMO_S_etl_load_comments',
               program_name => 'JOB_2'
           );

       dbms_scheduler.define_chain_rule(
          chain_name => 'DEMO_CHAIN',
           condition => '1=1',
          action => 'START DEMO_S_START',
        rule_name => 'DEMO_R_START'
      );

       dbms_scheduler.define_chain_rule(
            chain_name => 'DEMO_CHAIN',
            condition => 'DEMO_S_etl_load_articles SUCCEEDED',
            action => 'START DEMO_S_etl_load_comments',
            rule_name => 'DEMO_R_CONTINUE'
        );
    END;


    DECLARE
    start_date DATE := TO_DATE('2023-01-01', 'YYYY-MM-DD');
    end_date DATE := TO_DATE('2025-01-31', 'YYYY-MM-DD');
    p_current_date DATE := start_date;
BEGIN
    LOOP
         exit when p_current_date >= end_date;
        -- Add more debugging lines for other expressions if needed
        DBMS_OUTPUT.PUT_LINE(current_date);
        INSERT INTO SCD.DIM_DATES (
            COL_D_DATE,
            COL_D_YEAR,
            COL_HALF_YEAR,
            COL_D_QUARTER,
            COL_D_MONTH,
            COL_NAME_MONTH,
            COL_D_DAY,
            COL_D_WEEK,
            COL_BEGIN_OF_MONTH,
            COL_END_OF_MONTH
        ) VALUES (
            p_current_date,
            EXTRACT(YEAR FROM p_current_date),
           TO_NUMBER(EXTRACT(MONTH FROM p_current_date)),
            TO_NUMBER(CEIL(EXTRACT(MONTH FROM p_current_date) / 3)),
            TO_NUMBER(EXTRACT(MONTH FROM p_current_date)),
            TO_CHAR(current_date, 'Month'),
            TO_NUMBER( TO_CHAR( p_current_date, 'D')),
            TO_NUMBER(CEIL(EXTRACT(DAY FROM p_current_date)/7)),
            1,
           TO_NUMBER(TO_CHAR(LAST_DAY(p_current_date), 'DD'))
        );
        p_current_date := p_current_date + 1;
    END LOOP;

    COMMIT;
END;

BEGIN

  DBMS_SCHEDULER.ENABLE(
    name => 'BLOG_BASE.DEMO_CHAIN'
  );

  DBMS_SCHEDULER.RUN_CHAIN(
    'DEMO_CHAIN',
      ''
  );
END;

/
select * from dim_article;