CREATE USER blog_base IDENTIFIED BY "StrongP@ssw0rd";
CREATE USER blog_app IDENTIFIED BY "StrongP@ssw0rd";
CREATE USER blog_admin IDENTIFIED BY "StrongP@ssw0rd";

GRANT CREATE SESSION TO blog_base;
GRANT CREATE TABLE TO blog_base;
GRANT CREATE VIEW TO blog_base;
GRANT CREATE PROCEDURE TO blog_base;
GRANT CREATE TRIGGER TO blog_base;
GRANT CREATE SEQUENCE TO blog_base;
GRANT ALTER SESSION TO blog_base;
GRANT EXECUTE ON DBMS_SESSION TO blog_base;


GRANT CREATE SESSION TO blog_admin;
GRANT SELECT ON article_comment_v TO blog_admin;
GRANT EXECUTE ON tapi_audit TO blog_admin;

ALTER USER BLOG_BASE QUOTA UNLIMITED ON USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON article TO blog_app;
GRANT EXECUTE ON tapi_comment TO blog_app;

GRANT SELECT ON blog_base.ARTICLE TO SCD;
GRANT SELECT ON blog_base.ARTICLE_COMMENT TO SCD;
GRANT SELECT ON blog_base.AUDIT_ACTION TO SCD;
GRANT CREATE SESSION TO SCD;
GRANT CREATE TABLE TO SCD;
GRANT CREATE VIEW TO SCD;
GRANT CREATE PROCEDURE TO SCD;
GRANT CREATE TRIGGER TO SCD;
GRANT CREATE SEQUENCE TO SCD;
GRANT ALTER SESSION TO SCD;
GRANT EXECUTE ON SYS.DBMS_SCHEDULER TO SCD;
GRANT EXECUTE ON SYS.DBMS_ISCHED TO SCD;
ALTER USER SCD QUOTA UNLIMITED ON USERS;