CREATE TABLE article(id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    col_crt_dt date default sysdate NOT NULL ,
    col_mod_dt date default sysdate NOT NULL ,
    col_author varchar2(128) NOT NULL ,
    col_title varchar2(50) NOT NULL ,
    col_content clob NOT NULL,
    CONSTRAINT tab_article_pk  primary key (id)
);
 CREATE TABLE article_comment (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    col_article_id NUMBER NOT NULL,
    col_ts TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    col_reply_to_id NUMBER,
    col_rating int,
    col_votes int,
    col_commenter varchar2(128) not null,
    col_content clob not null,
  constraint article_fk_article_comment  FOREIGN KEY  (col_reply_to_id) REFERENCES article_comment(id),
  constraint article_comment_fk_article_comment FOREIGN KEY (col_article_id) REFERENCES article(id) ON DELETE CASCADE,
  constraint tab_article_comment primary key (id)

)
PARTITION BY RANGE (col_ts)
(
     PARTITION part_2022 VALUES LESS THAN (TIMESTAMP '2022-01-01 00:00:00'),
    PARTITION part_2023 VALUES LESS THAN (TIMESTAMP '2023-01-01 00:00:00'),
    PARTITION part_2024 VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00'),
    partition part_max values less than (maxvalue)
    -- Add more partitions for future years if needed
);
create table audit_action (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    col_ts timestamp(0) NOT NULL,
    col_table_name varchar2(128) NOT NULL,
    col_user_name varchar2(128) NOT NULL,
    col_action_type CHAR(1) CHECK (col_action_type IN ('I', 'U', 'D')) NOT NULL,
    col_action_summary varchar2(250) NOT NULL,
    constraint tab_audit_action_ck_action_type check (  col_action_type IN ('I', 'U', 'D')),
    constraint tab_article_audit primary key (id));



ALTER TABLE AUDIT_ACTION ADD COL_TABLE_ID INT;

